#!/usr/bin/env bash
# GTT - Session Memory Service entry point (ADE-independent).
#
# Regenerates gtt/SESSION.md via gtt-status.sh, verifies it, and prints a
# payload an ADE adapter can hand to its agent at session start:
#
#   GTT-SESSION-CONTEXT header (operational-only, no authority)
#   ---
#   <contents of gtt/SESSION.md>
#
# This script knows nothing about any ADE. Each ADE's adapter calls it and
# translates its stdout into whatever that ADE consumes. It fails loudly - a real non-zero exit and a message on
# stderr - instead of returning a partial or empty context.
#
# The payload is session memory: derived from repository state, operational
# only. NOT authority, NOT evidence, NOT a decision record, NOT a grounding
# source. It never outranks gtt/context/, gtt/adr/, or gtt/backlog.md.
#
# Usage:
#   gtt/scripts/gtt-session-context.sh
#
# Exit 0 = payload on stdout, 2 = cannot produce it (message on stderr).

set -euo pipefail

# Run from the project root regardless of the caller's cwd.
cd "$(dirname "$0")/../.."

fail() {
  echo "gtt-session-context: $*" >&2
  exit 2
}

# `command -v python3` alone is not reliable on Windows: a stub python3.exe
# under WindowsApps satisfies it while actually only printing a Microsoft
# Store redirect and exiting non-zero. Probe each candidate with a real
# no-op invocation instead of trusting PATH presence.
PY=""
for candidate in python3 python; do
  if command -v "$candidate" >/dev/null 2>&1 && "$candidate" -c "" >/dev/null 2>&1; then
    PY="$candidate"
    break
  fi
done
[ -n "$PY" ] || fail "no working Python 3 interpreter found (tried python3, python)."

[ -f gtt/scripts/gtt-status.sh ] || fail "gtt/scripts/gtt-status.sh not found."
[ -f gtt/scripts/gtt_artifacts.py ] || fail "gtt/scripts/gtt_artifacts.py not found."

# gtt-status.sh tolerates a failing identity summary (it prints "cannot
# determine" into the report). For session context that failure must be
# visible, so exercise the same engine here and surface a real error.
if ! "$PY" gtt/scripts/gtt_artifacts.py summary >/dev/null 2>&1; then
  fail "gtt_artifacts.py summary failed - run it directly to see why."
fi

STATUS_ERR="$(bash gtt/scripts/gtt-status.sh 2>&1 >/dev/null)" \
  || fail "gtt-status.sh failed: ${STATUS_ERR}"

[ -s gtt/SESSION.md ] || fail "gtt/SESSION.md is missing or empty after gtt-status.sh."
grep -q "Generated by gtt/scripts/gtt-status.sh" gtt/SESSION.md \
  || fail "gtt/SESSION.md was not generated by gtt-status.sh; refusing to present it as session memory."

cat <<'EOF'
GTT-SESSION-CONTEXT
kind: session memory - operational-only, derived from repository state
authority: none. NOT authority, NOT evidence, NOT a decision record, NOT a grounding source.
precedence: gtt/context/ (L0) > gtt/adr/ (L1) > gtt/backlog.md > this. On any conflict, this loses.
source: gtt/SESSION.md, regenerated by gtt/scripts/gtt-status.sh
---
EOF
cat gtt/SESSION.md
