#!/usr/bin/env bash
# GTT - Markdown canonical-reference gate.
#
# Every .md file in the GTT kit must contain, at the top, the exact
# canonical reference:
#
#   https://github.com/GTT-Community/gtt-method/blob/main/GTT-CANONICAL-v2.1.md
#
# Deterministic, read-only: reports every file checked and its result,
# never modifies anything. Scope is exactly the GTT kit - the portable
# core at the project root, everything under gtt/ except derived/generated
# artifacts (gtt/SESSION.md - regenerated by gtt-status.sh, never
# hand-authored), and the ADE adapter instruction/skill/rule files. Files
# outside this kit (README.md, LICENSE, this repository's own
# GTT-CANONICAL source under .gtt-method/ if present, arbitrary project
# content) are intentionally out of scope - this is a GTT rule, not a
# repository-wide Markdown style rule.
#
# Usage:
#   gtt/scripts/gtt-check-markdown.sh
#
# Exit 0 = every file has the reference, 1 = at least one is missing it.

set -uo pipefail

URL="https://github.com/GTT-Community/gtt-method/blob/main/GTT-CANONICAL-v2.1.md"
FAIL=0

files=()
for f in AGENTS.md README-GTT.md README-GTT.es.md; do
  [ -f "$f" ] && files+=("$f")
done
while IFS= read -r f; do
  files+=("$f")
done < <(find gtt -name "*.md" ! -name "SESSION.md" 2>/dev/null | sort)
while IFS= read -r f; do
  files+=("$f")
done < <(find .claude .kiro .copilot -name "*.md" 2>/dev/null | sort)

echo "GTT Markdown Check"
echo

for f in "${files[@]}"; do
  if grep -qF "$URL" "$f" 2>/dev/null; then
    echo "PASS  $f"
  else
    echo "FAIL  $f"
    FAIL=1
  fi
done

echo
if [ "$FAIL" -ne 0 ]; then
  echo "gtt-check-markdown: FAILED - one or more GTT .md files are missing the canonical reference."
  exit 1
fi
echo "gtt-check-markdown: OK"
exit 0
