#!/usr/bin/env bash
# GTT - status. Deterministic snapshot of current/governed/pending/proposed/
# blocked/frozen state, derived from repository artifacts rather than any
# ADE's private conversation memory - so the same project resumes the same
# way whether the next session is Claude Code, Codex, Kiro, or Copilot.
#
# Also regenerates gtt/SESSION.md with the same content. That file is a
# DERIVED artifact, like gtt/protection/registry.yaml: never hand-edited,
# safe to regenerate at any time, and never loaded automatically by any
# agent - it is operational context, not architectural authority, evidence,
# or a substitute for an ADR/decision record.
#
# Usage:
#   gtt/scripts/gtt-status.sh
#
# Exit 0 always (a status report that could fail to run would defeat its
# own purpose - if something below is missing, the report says so).

set -uo pipefail

OUT="gtt/SESSION.md"

adapters=()
[ -d ".claude" ] && adapters+=("claude")
[ -d ".kiro" ] && adapters+=("kiro")
[ -f ".copilot/copilot-instructions.md" ] && adapters+=("copilot")

if [ "${#adapters[@]}" -eq 1 ]; then
  ADE_LINE="${adapters[0]}"
elif [ "${#adapters[@]}" -eq 0 ]; then
  ADE_LINE="none detected"
else
  ADE_LINE="catalog (multiple adapters present: ${adapters[*]} - normal for the gtt-bootstrap source repo, not for an installed project)"
fi

if [ -f "gtt/.frozen" ]; then
  FREEZE_LINE="frozen ($(head -1 gtt/.frozen 2>/dev/null))"
else
  FREEZE_LINE="pre-freeze (gtt/context/ and gtt/adr/ are agent-writable)"
fi

IN_PROGRESS=""
BLOCKED=""
if [ -f "gtt/backlog.md" ]; then
  IN_PROGRESS="$(grep -B2 -E '^\s*-\s*\*\*Status:\*\*\s*In Progress\s*$' gtt/backlog.md 2>/dev/null | grep -oE '^##### STORY-[0-9]+.*' || true)"
  BLOCKED="$(grep -B2 -E '^\s*-\s*\*\*Status:\*\*\s*Blocked\s*$' gtt/backlog.md 2>/dev/null | grep -oE '^##### STORY-[0-9]+.*' || true)"
fi

PENDING_PROPOSALS="$(cd gtt/proposals 2>/dev/null && find . -maxdepth 1 -type f ! -name 'README.md' | sed 's|^\./||' || true)"

CR_STATE="no gtt/CHANGE-REQUEST.md found"
if [ -f "gtt/CHANGE-REQUEST.md" ]; then
  if grep -qE '^Change: <' gtt/CHANGE-REQUEST.md 2>/dev/null; then
    CR_STATE="empty (still template placeholders)"
  else
    CR_STATE="FILLED IN - review it, a change request is waiting"
  fi
fi

ADRS=""
if [ -d "gtt/adr" ]; then
  ADRS="$(grep -H '^- Status:' gtt/adr/ADR-[0-9]*.md 2>/dev/null | sed -E 's#gtt/adr/##; s#:- Status:# - Status:#' || true)"
fi

GUARD_COUNT=0
if [ -f "gtt/protection/registry.yaml" ]; then
  GUARD_COUNT="$(grep -cE '^\s*-\s*artifact:' gtt/protection/registry.yaml 2>/dev/null)"
  GUARD_COUNT="${GUARD_COUNT:-0}"
fi

{
  echo "# GTT Session State"
  echo "#"
  echo "# Generated by gtt/scripts/gtt-status.sh. Derived, like a lockfile -"
  echo "# never hand-edited; re-run the script to refresh. Operational context"
  echo "# only: NOT architectural authority, NOT evidence, NOT a substitute for"
  echo "# an ADR or decision record."
  echo "#"
  echo "# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo
  echo "## ADE adapter"
  echo "${ADE_LINE}"
  echo
  echo "## Freeze state"
  echo "${FREEZE_LINE}"
  echo
  echo "## Current work (Stories In Progress)"
  if [ -n "$IN_PROGRESS" ]; then echo "$IN_PROGRESS"; else echo "none"; fi
  echo
  echo "## Blocked (Stories Blocked)"
  if [ -n "$BLOCKED" ]; then echo "$BLOCKED"; else echo "none"; fi
  echo
  echo "## Pending proposals (gtt/proposals/, excluding README.md)"
  if [ -n "$PENDING_PROPOSALS" ]; then echo "$PENDING_PROPOSALS"; else echo "none"; fi
  echo
  echo "## Change request"
  echo "${CR_STATE}"
  echo
  echo "## ADRs"
  if [ -n "$ADRS" ]; then echo "$ADRS"; else echo "none"; fi
  echo
  echo "## GTTGuard"
  echo "${GUARD_COUNT} protected artifact(s) in gtt/protection/registry.yaml"
} | tee "$OUT"

exit 0
