#!/usr/bin/env bash
# GTT - status. Deterministic snapshot of current/governed/pending/proposed/
# blocked/frozen state, derived from repository artifacts rather than any
# ADE's private conversation memory - so the same project resumes the same
# way whichever ADE picks it up. It describes GTT's operational state only and
# names no ADE: anything specific to an ADE lives in its adapter.
#
# Also regenerates gtt/SESSION.md with the same content. That file is a
# DERIVED artifact, like gtt/protection/registry.yaml: never hand-edited,
# safe to regenerate at any time, and never loaded automatically by any
# agent - it is operational context, not architectural authority, evidence,
# or a substitute for an ADR/decision record.
#
# Usage:
#   gtt/scripts/gtt-status.sh
#
# Exit 0 always (a status report that could fail to run would defeat its
# own purpose - if something below is missing, the report says so).

set -uo pipefail

OUT="gtt/SESSION.md"

if [ -f "gtt/.frozen" ]; then
  FREEZE_LINE="frozen ($(head -1 gtt/.frozen 2>/dev/null))"
else
  FREEZE_LINE="pre-freeze (gtt/context/ and gtt/adr/ are agent-writable)"
fi

IN_PROGRESS=""
BLOCKED=""
if [ -f "gtt/backlog.md" ]; then
  IN_PROGRESS="$(grep -B2 -E '^\s*-\s*\*\*Status:\*\*\s*In Progress\s*$' gtt/backlog.md 2>/dev/null | grep -oE '^##### STORY-[0-9]+.*' || true)"
  BLOCKED="$(grep -B2 -E '^\s*-\s*\*\*Status:\*\*\s*Blocked\s*$' gtt/backlog.md 2>/dev/null | grep -oE '^##### STORY-[0-9]+.*' || true)"
fi

PENDING_PROPOSALS="$(cd gtt/proposals 2>/dev/null && find . -maxdepth 1 -type f ! -name 'README.md' | sed 's|^\./||' || true)"

CR_STATE="no gtt/CHANGE-REQUEST.md found"
if [ -f "gtt/CHANGE-REQUEST.md" ]; then
  if grep -qE '^Change: <' gtt/CHANGE-REQUEST.md 2>/dev/null; then
    CR_STATE="empty (still template placeholders)"
  else
    CR_STATE="FILLED IN - review it, a change request is waiting"
  fi
fi

ADRS=""
if [ -d "gtt/adr" ]; then
  ADRS="$(grep -H '^- Status:' gtt/adr/ADR-[0-9]*.md 2>/dev/null | sed -E 's#gtt/adr/##; s#:- Status:# - Status:#' || true)"
fi

GUARD_COUNT=0
if [ -f "gtt/protection/registry.yaml" ]; then
  GUARD_COUNT="$(grep -cE '^\s*-\s*artifact:' gtt/protection/registry.yaml 2>/dev/null)"
  GUARD_COUNT="${GUARD_COUNT:-0}"
fi

# Artifact identity/index state and repository resume hints. Both are derived
# from the repository (manifest, index, git) - never from ADE memory.
PY=""
for candidate in python3 python; do
  if command -v "$candidate" >/dev/null 2>&1 && "$candidate" -c "" >/dev/null 2>&1; then
    PY="$candidate"
    break
  fi
done
ARTIFACT_STATE="cannot determine (no working Python 3 interpreter)"
if [ -n "$PY" ] && [ -f "gtt/scripts/gtt_artifacts.py" ]; then
  ARTIFACT_STATE="$("$PY" gtt/scripts/gtt_artifacts.py summary 2>&1 || true)"
fi

GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "not a git repository")"
GIT_DIRTY="$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')"
GIT_RECENT="$(git log -5 --format='%h %s' 2>/dev/null || true)"

{
  echo "# GTT Session State"
  echo "#"
  echo "# Generated by gtt/scripts/gtt-status.sh. Derived, like a lockfile -"
  echo "# never hand-edited; re-run the script to refresh."
  echo "#"
  echo "# operational-only. NOT authority, NOT evidence, NOT a decision record,"
  echo "# NOT a grounding source, NOT a substitute for an ADR. Governed context"
  echo "# (gtt/context/, gtt/adr/) and gtt/backlog.md prevail over this file."
  echo "#"
  echo "# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo
  echo "## Freeze state"
  echo "${FREEZE_LINE}"
  echo
  echo "## Current work (Stories In Progress)"
  if [ -n "$IN_PROGRESS" ]; then echo "$IN_PROGRESS"; else echo "none"; fi
  echo
  echo "## Blocked (Stories Blocked)"
  if [ -n "$BLOCKED" ]; then echo "$BLOCKED"; else echo "none"; fi
  echo
  echo "## Pending proposals (gtt/proposals/, excluding README.md)"
  if [ -n "$PENDING_PROPOSALS" ]; then echo "$PENDING_PROPOSALS"; else echo "none"; fi
  echo
  echo "## Change request"
  echo "${CR_STATE}"
  echo
  echo "## ADRs"
  if [ -n "$ADRS" ]; then echo "$ADRS"; else echo "none"; fi
  echo
  echo "## GTTGuard"
  echo "${GUARD_COUNT} protected artifact(s) in gtt/protection/registry.yaml"
  echo
  echo "## Artifact identity and technical index"
  echo "${ARTIFACT_STATE}"
  echo
  echo "## Repository (resume hints)"
  echo "branch: ${GIT_BRANCH}; uncommitted paths: ${GIT_DIRTY}"
  if [ -n "$GIT_RECENT" ]; then echo "recent commits:"; echo "$GIT_RECENT"; fi
} | tee "$OUT"

exit 0
